### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by bohbra** [SignalR/java-client#10]
It would be nice if the jars were published to maven.  This would make it significantly easier to consume and get updates from this library.

**Comment by keyoh** [comment]
Using gradle and uploading the lib to maven are separate things.  Why is this closed?

**Comment by ncthbrt** [comment]
Please could you consider reponening this issue. For many projects, Gradle pulls dependencies from Maven Central. I'm developing a SDK which wraps SignalR for multiple platforms, and versioning would be far easier if the lib was available in the central Maven Repository.

**Comment by juanpmarin-infocorp** [comment]
You can use [https://jitpack.io](https://jitpack.io) to add the lib to gradle dependencies
[https://jitpack.io/#SignalR/java-client/master](https://jitpack.io/#SignalR/java-client/master)
