### ISSUE TITLE
InvalidHttpStatusCodeException doesn't give you the actual status code

### ISSUE THREAD

**Issue by paulirwin** [SignalR/java-client#102]
The InvalidHttpStatusCodeException (i.e. on a 401 Unauthorized response) doesn't have any way of determining whether the status code is an error (5xx) or a bad request (4xx). The exception type should have a getStatusCode() method.

I'll be submitting a PR for this shortly.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
