### ISSUE TITLE
Client creates 2x connections when using Long polling

### ISSUE THREAD

**Issue by katit** [SignalR/java-client#105]
Trying to make this work for Android devices. This is my code to connect to HUB:

```
public void Connect()
    {
        // Don't try to connect if not logged in or in Demo
        // TODO: if (Preferences.getInstance().getIsDemoMode() || !Preferences.getInstance().getIsUserAuthenticated()) return;


        // TODO: Make it work with self-signed certs
        hubConnection = new HubConnection("http://192.168.33.116/dbg", "", true, new NullLogger());
        hubConnection.getHeaders().put("SRUserId", "123456"); // TODO: Set UserId header

        final HubProxy hubProxy = hubConnection.createHubProxy("SignalRHub");
        hubProxy.subscribe(this);

        hubConnection.stateChanged(new StateChangedCallback()
        {
            @Override
            public void stateChanged(ConnectionState oldState, ConnectionState newState)
            {
                Log.d(LOG_TAG, "Connection STATE CHANGED from " + oldState + " to " + newState);
            }
        });

        // Work with long polling connections only. Don't deal with server sockets and we
        // don't have WebSockets installed
        SignalRFuture<Void> awaitConnection = hubConnection.start(new LongPollingTransport(new NullLogger()));
        try
        {
            awaitConnection.get();
        }
        catch (Exception e)
        {
            LogData.e(LOG_TAG, e, LogData.Priority.High);
        }
    }
```

I run it from Application.onStart. And then on server and Android side I see that there is 2 connections going on at the same time. I see them simultaneously connecting and re-connecting. Is that something expected?? This causes double messages received from server.

Also, what I noticed (bug?) with long polling - status "CONNECTED" is almost never set, because it's always in "RECONNECTING" state which is technically correct, but code in HubConnection.onReceive checks on status and won't raise hub events unless it's connected. So, unless that filter "IF" removed - there will be only random messages received from server (race condition)

**Comment by Fi5t** [comment]
This project is dead. I'm sorry.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
