### ISSUE TITLE
WebsocketTransport overrides onClosed Runnable callback

### ISSUE THREAD

**Issue by engineers-bojan** [SignalR/java-client#108]
I was trying to work around the issue of being stuck at Reconnecting state. It happens on both wifi and 3g networks after a few successful reconnections. 

I applied the suggested fix https://github.com/SignalR/java-client/issues/74  added the triggerError call in onError handling and the connection now updates its state to Disconnected but the closed callback was never called on my handler.

Debugging the issue i found out that the WebsocketTransport overrides the connection.closed handler and thus this callback doesnt get invoked.

I would also like to note that the closed callback gets overriden only in the case if the connection was successful but then lost. If i start the app without a valid internet connection the closed callback is invoked properly...

Shouldnt the user set callbacks on the connection be preserved? I am using the closed callback to initiate a reconnect attempt if network and app conditions allow it, this way the callback is lost forever..

Edit 1: Just wanted to add, this issue is easily worked around by using the StateChangedCallback, but i think the above mention should be at least noted via documentation.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
