### ISSUE TITLE
Client can't handle a .NET server that sends types

### ISSUE THREAD

**Issue by shlatchz** [SignalR/java-client#111]
Hello, I have an android java client and a .NET SignalR hub.
The client tries to receive a complex response, which contains "$type" and "$values" objects in the "A" object. 

```
{
  "$type": "Microsoft.AspNet.SignalR.Hubs.ClientHubInvocation, Microsoft.AspNet.SignalR.Core",
  "H": "CoolHub",
  "M": "GetStuff",
  "A": {
    "$type": "System.Object[], mscorlib",
    "$values": [
      {
        "$type": "System.Collections.Generic.List`1[[System.Tuple`2[[System.Int64, mscorlib],[System.Collections.Generic.List`1[[Client.Common.SomeClass, Client.Common]], mscorlib]], mscorlib]], mscorlib",
        "$values": [
          {
                ...
          }
        ]
      }
    ]
  }
}
```

Because of that the client errors and disconnects with the following:

> com.android.com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT 

How can the java client set `TypeNameHandling = TypeNameHandling.All` like in C#?

Thanks!

**Comment by davidfowl** [comment]
It can't. That's a JSON.NET thing. You need to use regular JSON...

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
