### ISSUE TITLE
JITPack + Gradle/Maven Repository maintenance.

### ISSUE THREAD

**Issue by ChrisCates** [SignalR/java-client#114]
I would be more then happy to maintain this segment of the project for you guys.

Let me know if you are open to a pull request updating docs and uploading the .jar file to JITPack so I can more easily use this tool in my Java projects.

Thanks so much,
Chris

PS: Please send me an email at hello@chriscates.ca everytime you update the jar so I can update the JITPack.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
