### ISSUE TITLE
Connect to a server using SSL

### ISSUE THREAD

**Issue by Gaket** [SignalR/java-client#116]
Hello!

I am trying to make a connection to a server with a private certificate. I have a .cer file and can create SSL socket factory. The question is how to connect this socket factory to WebSockets transport and how to make other transports (in case if WebSocket fails) work with SSL?

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
