### ISSUE TITLE
java-client hangs forever on HubConnection.start()

### ISSUE THREAD

**Issue by rossbrigoli** [SignalR/java-client#117]
When the SignalR server has no Web Socket or Server-sent events capability, the java client hangs forever on HubConnection.start(). The SignalRFuture.get() does not fire up. In the code below, the awaitConnection.get() hangs.

```
   	hubConnection = new HubConnection(hubURL);
        hubProxy = hubConnection.createHubProxy(HUB_NAME);	        
        SignalRFuture<Void> awaitConnection = hubConnection.start();
        
        try {
        	awaitConnection.get();
        }
        catch (Exception ex) {
        	Log.error(ex.getMessage(), ex);
        }
```
My SignalR server is a sellf-hosted (OWIN) Windows service which does not have support for Web-socket or Server-sent events.

Known workaround: Use the overload start(final ClientTransport transport) instead of start() and provide an instance of LongPollingTransport.

**Comment by sepehr1101** [comment]
is this project dead?

**Comment by matthewbahr** [comment]
Seems like it. No code changed in 2 years...

**Comment by Marcosmemo** [comment]
what did you do to solve this?

**Comment by matthewbahr** [comment]
Personally (Can't speak for the others here) we ended up disabling web sockets. 

We're now looking to rip SigR out of the code and replace it with something else entirely.

**Comment by Marcosmemo** [comment]
How did you disabled the websocket? Can be done on the client side or there's something special i need to do?
Can you give me a example please.

**Comment by rossbrigoli** [comment]
i mentioned the workaround above. Don't use the default start() method. Use the overload method and tell it to use longpolling.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
