### ISSUE TITLE
SignalR 2.2.2 Client

### ISSUE THREAD

**Issue by PranKe01** [SignalR/java-client#118]
Hi,
some days ago SignalR 2.2.2 has been released. The clients for .Net and JavaScript has been updated - but the Java version did not.
Is there a new version coming soon?

Best regards!

**Comment by kkocabiyik** [comment]
I asked over Twitter and David said "unfortunately no" :(

**Comment by zhuxiaogit** [comment]
hey bro! this lib fix websocket bugs on android or java:
[https://github.com/zhuxiaogit/java-client](url)

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
