### ISSUE TITLE
JDK 1.8 and Android support

### ISSUE THREAD

**Issue by mrugendra** [SignalR/java-client#119]
It seems SignalR java client is being compiled with Java 8 / JDK 1.8, 
while to use it in android project, it should have a backward compatibility and should have been compiled with JDK 1.7. 

is this fix coming soon? I see that there is a open PR [https://github.com/SignalR/java-client/pull/77](https://github.com/SignalR/java-client/pull/77), are moderators aware of this issue and a possible fix?

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
