### ISSUE TITLE
How to get data from server?

### ISSUE THREAD

**Issue by bonvoathtanson** [SignalR/java-client#121]
- I'm try to access to method in server with return value but don't success. I have method as bellow:
public List<int> GetValues()
{
      List<int> values = new List<int>();
      values.Add(1);
      values.Add(2);
      return values;
}
Anyone could help show me how to invoke with this method?

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
