### ISSUE TITLE
NullPointerExcepetion -> microsoft.aspnet.signalr.client.Connection.reconnect()

### ISSUE THREAD

**Issue by nicknabdullah** [SignalR/java-client#122]
Similar issue was opened before #24, and closed without mentioning solution.
However, it is occurring quite frequently in the latest version.

**Comment by dainekokate** [comment]
Hi. 
The same happend to me. Did you find solution?

**Comment by nicknabdullah** [comment]
Hi @dainekokate 
Unfortunately not.

**Comment by kkocabiyik** [comment]
What type of transport are you using? I guess the best transport to use over Android is ServerSentEvents. I'm even not able to make it work with WebSocket.

**Comment by nicknabdullah** [comment]
@kkocabiyik 
Agree, I've set transport to ServerSentEvents.

@dainekokate 
Couldn't get to the root of this exception, so I applied a check in **Connection.reconnect()** and build the sdk:

In **signalr-client-sdk/src/.../Connection.java** 

Changed the reconnect method:

```
private void reconnect() {
      if (mState == ConnectionState.Connected) {
            log("Stopping Heartbeat monitor", LogLevel.Verbose);
            mHeartbeatMonitor.stop();
            log("Restarting the transport", LogLevel.Information);
            startTransport(mHeartbeatMonitor.getKeepAliveData(), true);
      }
}
```
to 

```
private void reconnect() {
      if (mState == ConnectionState.Connected) {
            if(mHeartbeatMonitor!=null) {
                log("Stopping Heartbeat monitor", LogLevel.Verbose);
                mHeartbeatMonitor.stop();
                log("Restarting the transport", LogLevel.Information);
                startTransport(mHeartbeatMonitor.getKeepAliveData(), true);
            }
            else {
                log("Restarting the transport", LogLevel.Information);
                startTransport(mKeepAliveData, true);
            }
      }
}
```

After that, the exceptions seems to have been largely reduced.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
