### ISSUE TITLE
TCP Signal R Connection Issue

### ISSUE THREAD

**Issue by freeknortier** [SignalR/java-client#125]
When I have a TCP connection open from the mobile device to another device on the network the Signal R on the mobile device is unable to communicate to a server. The send command is sent without an issue but the response from the server never executes. When the TCP connection is closed then the Signal R works perfectly. Any suggestions?

![overview jpg](https://user-images.githubusercontent.com/21170567/29260993-7ca04822-80cd-11e7-8880-7383a4db7d4a.png)

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
