### ISSUE TITLE
Android: NegotiationException: There was a problem in the negotiation with the server

### ISSUE THREAD

**Issue by ankitthakkarsa** [SignalR/java-client#126]
We integrated code for android as per provided reference but we are getting error on connection.
Please find details below and looking for solution.  

```
Platform.loadPlatformComponent(new AndroidPlatformComponent());      
  String host = "https://serverURL";

        HubConnection connection = new HubConnection( host );
        HubProxy hub = connection.createHubProxy( "updates" );


        hub.subscribe("Feed:Post:Updated").addReceivedHandler(new Action<JsonElement[]>() {
            @Override
            public void run(JsonElement[] jsonElements) throws Exception {
                Log.e("TAG", "JsonElements received");
            }
        });


        SignalRFuture<Void> awaitConnection = connection.start();
        try {
            //awaitConnection.get();
            connection.start().get();
        } catch (InterruptedException e) {
            e.printStackTrace();
            // Handle ...
        } catch (ExecutionException e) {
            e.printStackTrace();
            // Handle ...
        }
```

**Error Logs:** 

`W/System.err: java.util.concurrent.ExecutionException: microsoft.aspnet.signalr.client.transport.NegotiationException: There was a problem in the negotiation with the server`

**Comment by hezhipengzipp** [comment]
wo too , then, how to detail with it?

**Comment by guisantogui** [comment]
I've got the same problem, we fixed it enabling signalR work with crossdomain. I didn't write any line of android code.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
