### ISSUE TITLE
Can't subscribe after reconnecting!

### ISSUE THREAD

**Issue by BMukhtar** [SignalR/java-client#127]
I am using signalR for chat application on android. I want to get notified on TeahcerAccepted, ChatReady, lessonChatReceived events that comes from server. I have created hubProxy for hubConnection, added subscriptions, this works very well (notifies everything(all events)) before reconnecting so after reconnecting ( HubConnection - Clearing invocation callbacks: Reconnecting) callbacks does not work although events are coming from server. Below the code of service class and logs

**SignarRService.java file**

`override fun onCreate() {
    super.onCreate()
    realm = Realm.getDefaultInstance()
    startSignalR()
}
private fun startSignalR() {
    Platform.loadPlatformComponent(AndroidPlatformComponent())

    val neededToken = TOKEN.replace("bearer ","")
    val logger = Logger { message, level -> logd(level.toString() +":  " + message,TAG_SIGNALR+"LogLevel") }

    mHubConnection = HubConnection("http://ututor.azurewebsites.net","authorization="+neededToken,true, logger)

    mHubProxy = mHubConnection!!.createHubProxy(SERVER_HUB_CHAT)

    mHubConnection!!.closed {
        logd("closed",TAG_SIGNALR)
        connectSignalR()
    }

    connectSignalR()

}
fun connectSignalR(){

    mHubProxy!!.subscribe(object : Any() {
        @SuppressWarnings("unused")
        fun TeacherAccepted(message: String){
            logd(message,TAG_SIGNALR)
            notifyTeacherAccepted(message)
        }
        @SuppressWarnings("unused")
        fun ChatReady(){
            notifyChatReady()
        }
        @SuppressWarnings("unused")
        fun lessonChatReceived(message: CustomMessage){
            logd(Gson().toJson(message, CustomMessage::class.java))
        }
    })

    val awaitConnection = mHubConnection!!.start(LongPollingTransport(mHubConnection!!.logger))
    try {
        awaitConnection.get()
    } catch (e: InterruptedException) {
        Log.e("onErrorOccured",e.toString())
    } catch (e: ExecutionException) {
        Log.e("onErrorOccured",e.toString())
    }

    mHubConnection!!.received( { json ->
        Log.e("onMessageReceived ", json.toString())
    })
}`

Logs i will get only important points from logs not all logs

`   Information:  HubConnection - Creating hub proxy: chat
 Information:  HubProxy chat - Subscribe to event ChatReady
 Information:  HubProxy chat - Creating new subscription for: chatready
 Information:  HubProxy chat - Subscribe to event TeacherAccepted
 Information:  HubProxy chat - Creating new subscription for: teacheraccepted
 Information:  HubProxy chat - Subscribe to event lessonChatReceived
 Information:  HubProxy chat - Creating new subscription for: lessonchatreceived
 Verbose:  HubConnection - Entered startLock in start

//Here must be connection process

 Verbose:  Request executed
 Verbose:  longPolling - Trigger onData with data: {"C":"d-300E3EC2-Hr,0|LH,0|Kd,5|LI,2|Kf,0","M":[{"H":"chat","M":"TeacherAccepted","A":[101]}]}
 Verbose:  HubConnection - Received data:
 Verbose:  MessageId received: d-300E3EC2-Hr,0|LH,0|Kd,5|LI,2|Kf,0
 Verbose:  Invoking OnReceived with: null
 Verbose:  HubConnection - Invoking messageReceived with: {"H":"chat","M":"TeacherAccepted","A":[101]}d: {"H":"chat","M":"TeacherAccepted","A":[101]}
 Information:  HubConnection - Processing message
 Verbose:  HubConnection - Getting HubInvocation from message
 Verbose:  HubConnection - Message for: chat
 Verbose:  HubConnection - Invoking event: teacheraccepted with arguments [101]
 Verbose:  HubProxy chat - Handling dynamic subscription: TeacherAccepted
 Verbose:  HubProxy chat - Invoking method for dynamic subscription: TeacherAccepted  //Callback was called

//Here must be unneccecary code
// Starts reconnecting

 Information:  HubConnection - Slow connection detected
 Information:  HubConnection - Timeout
 Verbose:  HubConnection - Stopping Heartbeat monitor
 Information:  HubConnection - Restarting the transport
 Verbose:  HubConnection - Entered startLock in startTransport
 Information:  HubConnection - Starting the transport
 Verbose:  HubConnection - Stopping heartbeat monitor
 Verbose:  HubConnection - Clearing invocation callbacks: Reconnecting  //Here clears
 Verbose:  HubConnection - Starting transport for Reconnection
 Verbose:  longPolling - Trigger onData with data: {"C":"d-300E3EC2-Hr,0|LH,0|Kd,6|LI,2|Kf,0","M":[{"H":"chat","M":"ChatReady","A":[]}]}
 Verbose:  HubConnection - Received data:
 Verbose:  MessageId received: d-300E3EC2-Hr,0|LH,0|Kd,6|LI,2|Kf,0
 Verbose:  Invoking OnReceived with: null    //Callbacks does not work`

How to resubscribe for events or do something else for this problem? Please help I can not decide for 3 days this problem.

if you need this is posted question link https://stackoverflow.com/questions/45856185/how-to-subscribe-to-hub-events-after-hubconnection-was-reconnected-in-signalr-on

**Comment by BMukhtar** [comment]
if you need this is posted question link https://stackoverflow.com/questions/45856185/how-to-subscribe-to-hub-events-after-hubconnection-was-reconnected-in-signalr-on

**Comment by wiselius** [comment]
Hi @BMukhtar,
Did you find a solution for this issue? I'm running into the same...

**Comment by BMukhtar** [comment]
No,  I have searched it,  it is unresolved issue, this project(SignarR for
Java and Android)  was stopped supporting almost 3 years,  so I think it
will not be supported  in the future,  I recommend you to use socket.io or
other libraries,  sorry for my English

**Comment by JorisPaul** [comment]
Okay, Thanks for the answer.
I just found a workaround for myself by using ServerSentEventsTransport instead of LongPolling.

**Comment by BMukhtar** [comment]
When I try this one it worked worse than long polling,  finally the best
solution was using long polling and when it starts reconnecting restart
connection and resubscribe, in this way it handles the most events than
other ways,  but some events does not occur, and this library does not
support websocket connection,  so that I strongly recommend you use
socket.io

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
