### ISSUE TITLE
Asp.NetCore SignalR

### ISSUE THREAD

**Issue by jagathprasanga** [SignalR/java-client#129]
Not connecting with Asp.NetCore SignalR Hubs.
Please help.

**Comment by moozzyk** [comment]
This client is not compatible with SignalR for Asp.Net Core. https://github.com/aspnet/SignalR/issues/1017

**Comment by jagathprasanga** [comment]
Is there any scheduled plan for release java client to Asp.Net Core SignalR.

**Comment by moozzyk** [comment]
It's on our ["Big Rocks" list](https://github.com/aspnet/SignalR/issues/394)
