### ISSUE TITLE
Is this library dead ?!

### ISSUE THREAD

**Issue by arsanjani** [SignalR/java-client#130]
3 years past from last commit!
lot of open issues!
can we trust to use this library in android application ?
what is the alternative solution for android client ?

**Comment by omerv2** [comment]
I'd highly recommend socket.io for different platforms such as android, ios.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
