### ISSUE TITLE
[Question] Support for Asp.net Core SignalR

### ISSUE THREAD

**Issue by adincebic** [SignalR/java-client#134]
Is there any hope that there will be a version that will support the new ASP.NET Core SignalR?

**Comment by davenewza** [comment]
Anything on this?  Otherwise, sample code on how to connect up using websockets would be handy.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
