### ISSUE TITLE
SignalR Service Hang the app

### ISSUE THREAD

**Issue by apptunixdeepshikha** [SignalR/java-client#137]
Hello,

We are using Background Service to establish the connection with sockets. But if there is some error while connecting then sockets reconnect. Due to reconnection my app freezes some time. Please help me to resolve this issue.

Thanks!

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
