### ISSUE TITLE
Getting exception randomly 

### ISSUE THREAD

**Issue by RanchhodRamani** [SignalR/java-client#142]
Please find the log.

`04-30 16:23:49.972 19377-19512/app.Easy W/System.err: java.io.EOFException
04-30 16:23:49.972 19377-19512/app.Easy W/System.err:     at com.android.okhttp.okio.RealBufferedSource.require(RealBufferedSource.java:64)
04-30 16:23:49.972 19377-19512/app.Easy W/System.err:     at com.android.okhttp.okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
04-30 16:23:49.973 19377-19512/app.Easy  W/System.err:     at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.readChunkSize(HttpConnection.java:479)
04-30 16:23:49.973 19377-19512/app.Easy W/System.err:     at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:460)
04-30 16:23:49.974 19377-19512/app.Easy W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
04-30 16:23:49.974 19377-19512/app.Easy W/System.err:     at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:287)
04-30 16:23:49.974 19377-19512/app.Easy W/System.err:     at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:350)
04-30 16:23:49.974 19377-19512/app.Easy W/System.err:     at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:179)
04-30 16:23:49.974 19377-19512/app.Easy W/System.err:     at java.io.InputStreamReader.read(InputStreamReader.java:184)
04-30 16:23:49.974 19377-19512/app.Easy W/System.err:     at java.io.BufferedReader.fill(BufferedReader.java:172)
04-30 16:23:49.974 19377-19512/app.Easy W/System.err:     at java.io.BufferedReader.readLine(BufferedReader.java:335)
04-30 16:23:49.974 19377-19512/app.Easy W/System.err:     at java.io.BufferedReader.readLine(BufferedReader.java:400)
04-30 16:23:49.974 19377-19512/app.Easy W/System.err:     at microsoft.aspnet.signalr.client.http.StreamResponse.readLine(StreamResponse.java:87)
04-30 16:23:49.974 19377-19512/app.Easy W/System.err:     at microsoft.aspnet.signalr.client.transport.ServerSentEventsTransport$1.onResponse(ServerSentEventsTransport.java:91)
04-30 16:23:49.974 19377-19512/app.Easy W/System.err:     at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:82)
04-30 16:23:49.975 19377-19512/app.Easy W/System.err:     at java.lang.Thread.run(Thread.java:761)
04-30 16:23:49.975 19377-19512/app.Easy W/System.err: java.io.EOFException
04-30 16:23:49.975 19377-19512/app.Easy W/System.err:     at com.android.okhttp.okio.RealBufferedSource.require(RealBufferedSource.java:64)
04-30 16:23:49.975 19377-19512/app.Easy W/System.err:     at com.android.okhttp.okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
04-30 16:23:49.975 19377-19512/app.Easy W/System.err:     at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.readChunkSize(HttpConnection.java:479)
04-30 16:23:49.976 19377-19512/app.Easy W/System.err:     at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:460)
04-30 16:23:49.976 19377-19512/app.Easy W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
04-30 16:23:49.976 19377-19512/app.Easy W/System.err:     at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:287)
04-30 16:23:49.976 19377-19512/app.Easy W/System.err:     at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:350)
04-30 16:23:49.976 19377-19512/app.Easy W/System.err:     at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:179)
04-30 16:23:49.976 19377-19512/app.Easy W/System.err:     at java.io.InputStreamReader.read(InputStreamReader.java:184)
04-30 16:23:49.976 19377-19512/app.Easy W/System.err:     at java.io.BufferedReader.fill(BufferedReader.java:172)
04-30 16:23:49.977 19377-19512/app.Easy W/System.err:     at java.io.BufferedReader.readLine(BufferedReader.java:335)
04-30 16:23:49.977 19377-19512/app.Easy W/System.err:     at java.io.BufferedReader.readLine(BufferedReader.java:400)
04-30 16:23:49.977 19377-19512/app.Easy W/System.err:     at microsoft.aspnet.signalr.client.http.StreamResponse.readLine(StreamResponse.java:87)
04-30 16:23:49.977 19377-19512/app.Easy W/System.err:     at microsoft.aspnet.signalr.client.transport.ServerSentEventsTransport$1.onResponse(ServerSentEventsTransport.java:91)
04-30 16:23:49.977 19377-19512/app.Easy W/System.err:     at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:82)
04-30 16:23:49.977 19377-19512/app.Easy W/System.err:     at java.lang.Thread.run(Thread.java:761)`

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
