### ISSUE TITLE
Reconnect event not working!

### ISSUE THREAD

**Issue by SaseGacev** [SignalR/java-client#25]
Im starting connection, then i stop website in iis, wait for 2-3 seconds then i start again. The clients never get in recconect state. In order to reconnect i must create new instance of HubConnection.

**Comment by jignesh6990** [comment]
Hi Ali,

We have tested well and found the issue that it display reconnecting status ever and not reconnect.When kill the app,it tries to make a new connection and also takes time to connect server hub.This scenario also happened with Wifi internet connection.
I have tested this same with window app.I have just a new connection with same signalR url which I have used with Java client and it successfully connected.
I have also added signalR connection code file in dropbox for your reference.
Source :https://www.dropbox.com/s/0wjvoyb310v4f29/SignalR%20Android%20Code.zip?dl=0
Could you please share signalR connection code for android?

Kindly guide us if anything wrong in signalR code.

Thanks a lot for your help and time.

Regards

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
