### ISSUE TITLE
Hangs on Sprint Network

### ISSUE THREAD

**Issue by bsonia** [SignalR/java-client#28]
In testing the java-client on several Sprint Android devices (US provider), I've had issues using the Sprint data network where it will hang/wait-for-timeout on the SignalRFuture<Void> get() line "mResultSemaphore.tryAcquire(timeout, unit)".

Works fine on AT&T and Verizon data networks and when the Sprint device is on WiFi.

I made a small change locally to SignalRFuture.java in microsoft.aspnet.signalr.client that appears to be working on all networks.  I simply updated this:

private Semaphore mResultSemaphore = new Semaphore(0);

to this:

private Semaphore mResultSemaphore = new Semaphore(1);

Just wanted to pass this on.

**Comment by cdeisler** [comment]
I think this issue should be addressed as I too saw the connection lock the entire java process with Semaphore(0).. changing it to 1 corrected the issue.

**Comment by ubeyou** [comment]
I had this issue on non US device, changing it to 1 corrected the issue. Thanks @bsonia.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
