### ISSUE TITLE
Calling hub.Invoke()  To many times causes an Exception

### ISSUE THREAD

**Issue by shimitapiro** [SignalR/java-client#30]
Hey,
I have been calling the invoke method of the HubProxy class, many times around 40 times each session and after 3 or 4 consecutive sessions the Application would crash with all kind of reasons like 

Caused by: android.os.TransactionTooLargeException
android.view.Surface$OutOfResourcesException: eglMakeCurrent failed EGL_BAD_ALLOC
java.lang.RuntimeException: Could not read input channel file descriptors from parcel.

After some investigating i realized that the error is from the invoke method and probably because it's creating to many InputStreamReader or something of that kind.

Hope to get your input about this soon

Thanks 
Shimi

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
