### ISSUE TITLE
Need to update repository

### ISSUE THREAD

**Issue by Blackmist** [SignalR/java-client#31]
http://maven.eclipse.org/ does not appear to exist any longer, so mvn package fails with the following error:

[ERROR] Failed to execute goal on project signalr-client-sdk: Could not resolve dependencies for project micros
oft.aspnet.signalr:signalr-client-sdk:jar:1.0: Failed to collect dependencies at com.google.code.gson:gson:jar:
2.2.2: Failed to read artifact descriptor for com.google.code.gson:gson:jar:2.2.2: Could not transfer artifact 
com.google.code.gson:gson:pom:2.2.2 from/to central (http://maven.eclipse.org/build): Connect to maven.eclipse.
org:80 [maven.eclipse.org/198.41.30.249] failed: Connection timed out: connect -> [Help 1]  
[ERROR]  
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.  
[ERROR] Re-run Maven using the -X switch to enable full debug logging.  
[ERROR]  
[ERROR] For more information about the errors and possible solutions, please read the following articles:  
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException                

Simply removing the repositories section from the pom, or changing the URL to http://repo.maven.apache.org/maven2 resolves this error.

To reproduce this behavior, clone the repository and run the following from the signalr-client-sdk folder:
mvn package

NOTE: if you have previously cached the Gson package on the build machine, you must first remove the cached bits by doing something like rm -r -f \users\username.m2\repository\com\google\code\gson. Otherwise, it will appear to work fine since it finds the bits locally.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
