### ISSUE TITLE
My app does not work in 3G connections

### ISSUE THREAD

**Issue by mohitsharmaniit11** [SignalR/java-client#33]
My app works well in WI-FI Connection. It works perfectly well in 2G as well but whenever i try to connect with 3G, it has issues and most of the time it don't make a connection sometime it makes connection after a long time (I am making a copy of Connection info in my database so i can check connection IDs from there), but rest of the part don't work. 

Kindly suggest what kind of changes do i need to apply for 3G connection as i know speed is not the concern because its working in 2G.

**Comment by wrustel** [comment]
Can I have the exactly code to see how do a properly 3G connection?. Also any Idea about how to do a reconnection when 3G fails or switch of connection point?

TY.

**Comment by arnoldpistorius** [comment]
The signalr java client will try to reconnect by itself when the connection is lost. In my case when I turn off wifi the connection is lost for a few seconds and will then be reconnected via mobile data.

The only code I use is:

```
HubConnection hubConnection = new HubConnection(url, "", true, new NullLogger());
HubProxy hubProxy = hubConnection.createHubProxy("myHubProxyName");

// All server events will be fired to this object!
hubProxy.subscribe(aSubscriptionObject);

hubConnection.closed(closedHandler);
hubConnection.reconnected(reconnectedHandler);
hubConnection.reconnecting(reconnectingHandler);
hubConnection.stateChanged(stateChangedHandler);
hubConnection.connectionSlow(connectionSlowHandler);
hubConnection.error(errorHandler);

// Start the connection!
LongPollingTransport transport = new LongPollingTransport(new NullLogger());
hubConnection.start(transport);
```
