### ISSUE TITLE
How can i Set Timeout for SignalR Technology Fallback in SignalR/Client Java

### ISSUE THREAD

**Issue by mohitsharmaniit11** [SignalR/java-client#34]
I know if a connection is not made SignalR will fallback from Websocket to SSE to ... to long pooling. I wanna know how can i set Timeout period for each technology to switch for example let us say if a connection is not made in 2 Sec then fallback to another technology. I wanna set those 2 Sec. 

How can i create this code in Android.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
