### ISSUE TITLE
Not able to run tests properly

### ISSUE THREAD

**Issue by sanketpatel2912** [SignalR/java-client#38]
HI,

I tried to run Android JUnit Test but console shows as following,

> [2014-11-05 10:55:10 - signalr-client-test-integration-android] Performing android.test.InstrumentationTestRunner JUnit launch
> [2014-11-05 10:55:10 - signalr-client-test-integration-android] Automatic Target Mode: Unable to detect device compatibility. Please select a target device.
> [2014-11-05 10:55:56 - signalr-client-test-integration-android] Uploading signalr-client-test-integration-android.apk onto device 'c160725e7185a8f'
> [2014-11-05 10:55:56 - signalr-client-test-integration-android] Installing signalr-client-test-integration-android.apk...
> [2014-11-05 10:56:01 - signalr-client-test-integration-android] Success!
> [2014-11-05 10:56:01 - signalr-client-test-integration-android] Launching instrumentation android.test.InstrumentationTestRunner on c160725e7185a8f
> [2014-11-05 10:56:01 - signalr-client-test-integration-android] Failed to launch test

How can i able to run all these signaR Tests via JUnit. And If i starts installed application manually and try to run checked tests, those are failing... with bellow log

> 11-05 11:01:00.415: D/SIGNALR-TEST-INTEGRATION(14919): TEST COMPLETED - Basic connection flow - ServerSentEvents - Failed - Ex: ExecutionException: java.net.SocketTimeoutException: failed to connect to /10.0.0.1 (port 10001) after 15000ms // >SocketTimeoutException: failed to connect to /10.0.0.1 (port 10001) after 15000ms //

**Comment by ShirinAnsari** [comment]
Hello Sanket. Facing the same issue, Did you found any solution to your problem?

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
