### ISSUE TITLE
Signalr Java client disconnected instead of reconnect

### ISSUE THREAD

**Issue by jignesh6990** [SignalR/java-client#39]
Hi
we are using SignalR java client for android app to receive signalr notifications.
We have noticed that when user off the wi-fi,it immediately disconnected from the server instead of calling onreconnect event.It should call to reconnect event and if internet not available with in 30 seconds then it should call to disconnect event.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
