### ISSUE TITLE
Crash dump on reconnect on Android app

### ISSUE THREAD

**Issue by eeshan-rocketuncle** [SignalR/java-client#41]
![screen shot 2014-11-14 at 3 33 13 pm](https://cloud.githubusercontent.com/assets/9738920/5042614/a76fda62-6c13-11e4-9c22-04591413a1dd.png)

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
