### ISSUE TITLE
Crash dump keeps coming in my android app

### ISSUE THREAD

**Issue by eeshan-rocketuncle** [SignalR/java-client#42]
![screen shot 2014-11-14 at 3 37 22 pm](https://cloud.githubusercontent.com/assets/9738920/5042640/2b317388-6c14-11e4-8435-ca72b58e2a9a.png)

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
