### ISSUE TITLE
when receiving 401 "unauthorised" from server my android app crash

### ISSUE THREAD

**Issue by BeshoyYoussef** [SignalR/java-client#46]
I use library of SignalR in my android app and when the server send 401 "unauthorised" the class library of SignalR crashed by this exception  and I can't handle it .. I put the code between try and catch but it still throw in SignalR library ...

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
