### ISSUE TITLE
Signalr publishing issue .. when add library .. 0 supported devices

### ISSUE THREAD

**Issue by BeshoyYoussef** [SignalR/java-client#47]
![signalr issue](https://cloud.githubusercontent.com/assets/9914261/5215288/6f9b3df0-762e-11e4-9353-a4dfbd8f4a2f.png)

when i add signalr libraries to my project and trying to upload it .. google play says 0 support devices as in the above image ..
then when i remove signalr libraries .. google play says 6320 devices supported.

**Comment by AresDev** [comment]
Some updates to this issue?

**Comment by BeshoyYoussef** [comment]
I have solved this issue by adding the signalr classes to my project .. not as a jar file.

**Comment by pschuette22** [comment]
@BeshoyYoussef How did you go about adding the signalr classes to the project?

**Comment by eak65** [comment]
I fixed the jars. https://github.com/eak65/FixedSignalRJar

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
