### ISSUE TITLE
How to Get a Value by  public <E> SignalRFuture<E> invoke(final Class<E> resultClass, final String method, Object... args)

### ISSUE THREAD

**Issue by hunter123321000** [SignalR/java-client#49]
## i try the way 1 (by handler)，i can recieve the result, code as below:

hub.on("receiveHelloWorldReturn",
                        new SubscriptionHandler1<String>() {
                            @Override
                            public void run(String msg) {

```
                            Log.i("0.03", "結果" + msg);
                            Toast.makeText(MainActivity.this, msg,
                                    Toast.LENGTH_LONG).show();
                        }
                    }, String.class);
            hub.invoke("HelloWorldReturn");
```

---
##  But i try the way 2 ( direct ), i can't receieve the result,

Class<String> resultClass = null;  
                SignalRFuture<String> str = hub.invoke(resultClass,
                        "HelloWorld2", "123");
                str.done(new Action<String>() {
                    @Override
                    public void run(String arg0) throws Exception {
                        Log.i("0.03", "arg0=" + arg0);
                    }
                }).onError(new ErrorCallback() {
                    @Override
                    public void onError(Throwable error) {
                        Log.i("0.03", "error=" + error.toString());
                    }
                });

---

Could Anyone help me, please...

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
