### ISSUE TITLE
LongPolling transport remains in reconnect state until server sends an event.

### ISSUE THREAD

**Issue by arnoldpistorius** [SignalR/java-client#54]
Hi,

I have an issue with the LongPolling transport. The problem is that when the server doesn't call any of the subscribed methods of the subscription object (provided through hubProxy.subscribe()), the signalr java client signals 'slow connection' and after a few seconds it will land in the reconnect state. When this happens, I am able to send data to the server using the hubProxy.invoke command while the client still stays in reconnect state. The data is handled as expected on the server. So no troubles here. But when I want to disconnect from the server, the connection remains open until the state has become 'reconnected'. The client will get only reconnected when the server invokes a subscription method on the client. So I am literally dependent of the server to call a method on my client side before I can close any connection.

Steps to reproduce:
1. start a connection with longpolling transport
2. create a hub proxy
3. wait until the connection gets in reconnect mode
4. perform some actions from the client to the server (which succeeds, while the connector says it isn't connected).
5. close the connection from the client
6. note that the connection doesn't disconnect
7. try to invoke a client method from the server
8. client gets reconnected and disconnected immediately.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
