### ISSUE TITLE
Does not Disconnect Instantly as connection in SignalR

### ISSUE THREAD

**Issue by mohitsharmaniit11** [SignalR/java-client#66]
SignalR Get Connect in an instant. But does not disconnect when the data Connection get closed automatically on the other hand if the Client is a browser Client gets disconnect in an instant if client is closed. Hence Creating Problem, How to disconnect in instant when Client loses Connectivity with Server

**Comment by arnoldpistorius** [comment]
Try to make a server command that closes the connection. Invoke it from your client.

**Comment by mohitsharmaniit11** [comment]
well if Internet Connection is down then How the server will be able to send a message to client to close the connection on the server. Client is not able to get connected due to lost connectivity but the server still having connection active and will have active content atleast for next 2 min. And any message that is delivered within those 2 minutes will get drop.

**Comment by arnoldpistorius** [comment]
This is how the SignalR longpolling mechanism works, the server is just waiting for the client to reconnect. Maybe you could try using WebSockets?

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
