### ISSUE TITLE
Failed to build application 

### ISSUE THREAD

**Issue by MMSaad** [SignalR/java-client#67]
once i added jar files and start build my app
Error:Execution failed for task ':app:preDexDebug'.

> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
>     C:\Users\AA\AppData\Local\Android\sdk\build-tools\21.1.2\dx.bat --dex --output C:\Users\AA\AndroidStudioProjects\TheMahen\app\build\intermediates\pre-dexed\debug\signalr-client-sdk-c4e83deedf5e75d371f36ddf7d9d040bf8a3121a.jar C:\Users\AA\AndroidStudioProjects\TheMahen\app\libs\signalr-client-sdk.jar
> Error Code:
>     1
> Output:
>     UNEXPECTED TOP-LEVEL EXCEPTION:
>     com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
>         at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
>         at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
>         at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
>         at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
>         at com.android.dx.command.dexer.Main.processClass(Main.java:704)
>         at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
>         at com.android.dx.command.dexer.Main.access$300(Main.java:83)
>         at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
>         at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
>         at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
>         at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
>         at com.android.dx.command.dexer.Main.processOne(Main.java:632)
>         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
>         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
>         at com.android.dx.command.dexer.Main.run(Main.java:246)
>         at com.android.dx.command.dexer.Main.main(Main.java:215)
>         at com.android.dx.command.Main.main(Main.java:106)
>     ...while parsing microsoft/aspnet/signalr/client/Action.class
>     1 error; aborting

build.gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

```
defaultConfig {
    applicationId "com.puretecheg.myapplication"
    minSdkVersion 14
    targetSdkVersion 21
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile files('libs/signalr-client-sdk-android.jar')
    compile files('libs/signalr-client-sdk.jar')
    compile files('libs/gson-2.2.2.jar')
}

**Comment by selcukermaya** [comment]
Same problem for me...

**Comment by Tooto** [comment]
same for me

**Comment by brunofdosreis** [comment]
Same here... some solution or workaround?

**Comment by brunofdosreis** [comment]
This worked for me: http://www.codeitive.com/vQSQyxXUkX/error-gradle-execution-failed-for-task-apppredexdebug.html

**Comment by sattha** [comment]
Same for me ..link dead

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
