### ISSUE TITLE
Android SignalR java-client: Not receiving all the SignalR messages on the HubConnection

### ISSUE THREAD

**Issue by raulbroto** [SignalR/java-client#71]
I've tried to receive the SignalR messages in several ways, but in any case I'm able to receive them always... I'm using the LongPollingTransport (maybe it is due to this), and I can see that the LongPolling log receives all the messages correctly but it only enters the handler method sometimes (in the others it seems to try to reconnect the server).

You can see more details on the StackOverflow question here: http://stackoverflow.com/questions/28587391/android-signalr-java-client-not-receiving-all-the-signalr-messages-on-the-hubco

I would really appreciate your help, because I'm are trying to move from SignalA (over a year without updates + some internal errors unhandled) to this library but at the moment I'm not able to receive all the messages, so I can't do it.

Many thanks!

**Comment by mirjalal** [comment]
@raulbroto have you solved your problem ?

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
