### ISSUE TITLE
ConnectionId is not obtained in some devices.

### ISSUE THREAD

**Issue by JoysonF** [SignalR/java-client#72]
I tried connecting the hub using con = new HubConnection(....) . This seems to work in most of the devices and i successfully get the connectionId .  The con.received(new MessageReceivedHandler() {  ...} gets called and it shows state as connected . However in some devices (tried with Moto X) it gives me state as connecting when con.start() is called but never gets connected .

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
