### ISSUE TITLE
Issue on Android

### ISSUE THREAD

**Issue by ooosv** [SignalR/java-client#73]
Hi,

I have an issue using SignalR SDK for Android. I did all the steps in order to integrate the SDK in my Android app (with Android Studio), but I'm facing a strange behavior: if I set the transport as:

// Start the connection
mHubConnection.start(new LongPollingTransport(logger)).done(new Action<Void>() {
            @Override
            public void run(Void obj) throws Exception {
                // Connection started!
            }
});

The client is not working in WiFi, and if I set the transport as:

  // Start the connection
  mHubConnection.start(new ServerSentEventsTransport(logger)).done(new Action<Void>() {
            @Override
            public void run(Void obj) throws Exception {
                // Connection started!
            }
  });

The client doesn't work on 3G.

If I set the transport as AutomaticTransport, the client doesn't work on both 3G and WiFi.

Why?

**Comment by pranavmehta** [comment]
I had a similar issue, turns out I was using an older version of the websockets jar. See my update [here] (https://github.com/SignalR/java-client/issues/79)

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
