### ISSUE TITLE
Android client not disconnect when stop server (lose connection)...stay in Reconnecting for ever !!! (WebsocketTransport)

### ISSUE THREAD

**Issue by aligorji** [SignalR/java-client#74]
hi
I'm run .net signalR server and use WebsocketTransport in android app,
every thing is good, but when stop server or turn off wifi  (lose connection), In this case works:

Connected > connectionSlow > reconnecting ... for ever!

I check and debug signalR's source code, I think there is a problem.

in microsoft.aspnet.signalr.client.Connection class,  (startTransport) method called when need connect to server (for ex). after connect call this section automatically: (in Connection.java > startTransport method)

<pre><code>
future.done(new Action<Void>() {
                    @Override
                    public void run(Void obj) throws Exception {
                        synchronized (mStartLock) {
....
</code></pre>

in HeartbeatMonitor class when disconnect server called bold section:

<pre><code>
if (timeElapsed >= mKeepAliveData.getTimeout()) 
{
      if (!mTimedOut)
     {
          // Connection has been lost
          mTimedOut = true;
          <b>mOnTimeout.run();</b>
      }
 }

</code></pre>

and then ....... call  (startTransport) again. but this time not raise 

<pre><code>
...
future.done(new Action<Void>() {
...

</code></pre>

also in WebsocketTransport class and this section:

 <pre><code>

mWebSocketClient = new WebSocketClient(uri) {
            @Override
            public void onOpen(ServerHandshake serverHandshake) {
                mConnectionFuture.setResult(null);
            }

            @Override
            public void onMessage(String s) {
                callback.onData(s);
            }

<b>
            @Override
            public void onClose(int i, String s, boolean b) {
                mWebSocketClient.close();
            }
</b>
            @Override
            public void onError(Exception e) {
                mWebSocketClient.close();
            }

</code></pre>

worked very good and when stoped server, raise onClose method of WebSocketClient class and it was shown that is working very good.

This has made me very confused  :(

i'm sorry for bad english

**Comment by aligorji** [comment]
i fined a bug !
when reconnecting, web socket event onError called. and error message is:

<pre>
<code>
connect to /192.168.13.3 (port 5005): connect failed: ECONNREFUSED (Connection refused)
</code>
</pre>

it's ok, becuase connection is lost. but signalR state in client stay Reconnecting.
when onError websocket , signalR library does not reaction

**Comment by jignesh6990** [comment]
Hi @aligorji 

Did you find any solution for this issue?

I have the same scenario in android when internet connection is slow signalR connections goes in reconnecting states forever.
If you found solution for this bug please post it so it really helps others.


Thanks
Jignesh

**Comment by aligorji** [comment]
Hi @jignesh6990
I've found scenarios that lead to bugs.
At the beginning of the process of connecting client to server in signalR, client will send an Http request (negotiation and handshake) to server and if it fails, throw exception Immediately
but
for web-socket errors, no solution has been provided.
at the bottom I got the problem solved.

---state is Disconnected
connect command
---state is Connecting
connected client to server   ...   
---state is Connected
lose connection or stop server application  ...  
[Client side]
raise onClose() web-socket transport (it's normal)
`HeartbeatMonitor` not received keep-alive packet from server, because connection is lose...
after some second ... 
---state is SlowConnection
after some second ... 
---state is ReConnecting
try connect to server again...(automatically)
<b><i>if connect to server successful</i></b>
---state is ReConnected
<i>and continue...</i>
<b><i>else</i></b>
raise onError() web-socket transport (it's normal)
end!!!!!
<b>bug!</b>
when error in web-socket not feedback to user or other module!!
---state is ReConnecting   <i>for ever!!!!</i>

i'm fixed this problem.

in `signalr-client-sdk` project
in `WebsocketTransport.java`

change this section:
<pre>
@Override
public void onError(Exception e) 
{
      mWebSocketClient.close();
}
</pre>
to
<pre>
@Override
public void onError(Exception e) 
{
      mWebSocketClient.close();
      <b>mConnectionFuture.triggerError(e);</b>
}
</pre>

it's worked.
In this case, when couldn't connect to server, throw exception and 
---state is Dissonnected

**Comment by aligorji** [comment]
next bug related to , when publish signalR web application on IIS, android client signalR error on connecting.
`#unkonow shemehttp`

fixed this problem.

in `signalr-client-sdk` project
in `transport/WebsocketTransport.java`

change this section:
<pre>
        URI uri;
        try {
            uri = new URI(url);
        } catch (URISyntaxException e) {
            e.printStackTrace();
            mConnectionFuture.triggerError(e);
            return mConnectionFuture;
        }
</pre>
<pre>
        URI uri;
        try {
            uri = new URI(url.replaceFirst("http://", "ws://"));
        } catch (URISyntaxException e) {
            e.printStackTrace();
            mConnectionFuture.triggerError(e);
            return mConnectionFuture;
        }
</pre>

**Comment by jignesh6990** [comment]
Hi Ali,

Let me give you brief about my app.
We have implemented real time mobile android app using java client.
Backend service is implemented using C#.Net and signalR hub is implemented in service.Everything is working fine but we are facing issue with connection.
We have tested and found that when wifi connection is there it immediately made the connection with server hub and deliver the messages.
But in real scenario when there's 3G or low internet connectivity the connection could not established or takes time to connect server hub and also not deliver the notification messages.
I have enabled the log and monitor connections life cycle.I found that the connection established and goes in reconnect mode immediately.Sometime it reconnect and sometimes not.

Thanks & regards
Jignesh

**Comment by aligorji** [comment]
Hi
>Sometime it reconnect and sometimes not.

reconnect error ? or not try for reconnecting ?

**Comment by jignesh6990** [comment]
It could not reconnect and just displaying status as reconnecting ever.Then need to kill the app and restart again makes new connection.

**Comment by aligorji** [comment]
i'm solved this problem at top.However,do you have problems ?

However, I am in my project, deleted completely process Reconnecting!!!
then manage it manually.
i remove `HeartbeatMonitor` and every thing about reconnecting!!!
but after fixed this bug(reconnecting for ever) I think to use it in normal mode.

**Comment by jignesh6990** [comment]
Hi Ali,

We have tested well and found the issue that it display reconnecting status ever and not reconnect.When kill the app,it tries to make a new connection and also takes time to connect server hub.This scenario also happened with Wifi internet connection.
I have tested this same with window app.I have just a new connection with same signalR url which I have used with Java client and it successfully connected.
I have also added signalR connection code file in dropbox for your reference.
Source :https://www.dropbox.com/s/0wjvoyb310v4f29/SignalR%20Android%20Code.zip?dl=0
Could you please share signalR connection code for android?

Kindly guide us if anything wrong in signalR code.

Thanks a lot for your help and time.

Regards

**Comment by aligorji** [comment]
Hi
I can't test (Realistically) your code.
It's seem no problem in your code.
the problem is signalr library. 

test it:
https://www.dropbox.com/s/3ut94l9gg110bri/signalr-client-sdk-android-release.aar?dl=0

**Comment by jignesh6990** [comment]
Hi Ali,

Thank you for your help.

I will test using this sdk and let you know more on this.

Thanks & Regards

**Comment by frared358** [comment]
I am trying to disconnect the SignalR connection from server in android app.. but it is not working and it making my app Freeze..

please help me..
