### ISSUE TITLE
Websockets - There was a problem in the negotiation with the server

### ISSUE THREAD

**Issue by tmedanovic** [SignalR/java-client#82]
Problem with websockets (I think because java.lang.NoClassDefFoundError: microsoft.aspnet.signalr.client.transport.WebsocketTransport$1), here is code that causes error:

```java
Toast.makeText(this, "Service Start", Toast.LENGTH_LONG).show();
Platform.loadPlatformComponent(new AndroidPlatformComponent());
String server = "http://mysite.com/api/signalr";

HubConnection connection = new HubConnection(server, true);
HubProxy proxy = connection.createHubProxy("conversationHub");

try {
	connection.start().get();
} catch (InterruptedException e) {
	e.printStackTrace();
} catch (ExecutionException e) {
	e.printStackTrace();
}

//Then call on() to handle the messages when they are received.
proxy.on("newConversationMessage", new SubscriptionHandler1<Payload>() {
	@Override
	public void run(Payload msg) {
		Log.d("result := ", msg.getText());
	}
}, Payload.class);
```

6-14 18:15:12.509  18195-18195/com.some.app I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<microsoft.aspnet.signalr.client.transport.WebsocketTransport$1>
06-14 18:15:12.510  18195-18195/com.some.app I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<microsoft.aspnet.signalr.client.transport.WebsocketTransport$1>
06-14 18:15:14.648  18195-18271/com.some.app I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<microsoft.aspnet.signalr.client.transport.WebsocketTransport$1>
06-14 18:15:14.696  18195-18195/com.some.app W/System.err﹕ java.util.concurrent.ExecutionException: microsoft.aspnet.signalr.client.transport.NegotiationException: There was a problem in the negotiation with the server
06-14 18:15:14.712  18195-18205/com.some.app W/art﹕ Suspending all threads took: 6.826ms
06-14 18:15:14.712  18195-18195/com.some.app W/System.err﹕ at microsoft.aspnet.signalr.client.SignalRFuture.get(SignalRFuture.java:112)
06-14 18:15:14.712  18195-18195/com.some.app W/System.err﹕ at microsoft.aspnet.signalr.client.SignalRFuture.get(SignalRFuture.java:102)
06-14 18:15:14.713  18195-18195/com.some.app W/System.err﹕ at com.some.app.service.NotifyService.onStart(NotifyService.java:47)
06-14 18:15:14.713  18195-18195/com.some.app W/System.err﹕ at android.app.Service.onStartCommand(Service.java:458)
06-14 18:15:14.713  18195-18195/com.some.app W/System.err﹕ at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2918)
06-14 18:15:14.713  18195-18195/com.some.app W/System.err﹕ at android.app.ActivityThread.access$2100(ActivityThread.java:149)
06-14 18:15:14.713  18195-18195/com.some.app W/System.err﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
06-14 18:15:14.713  18195-18195/com.some.app W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
06-14 18:15:14.713  18195-18195/com.some.app W/System.err﹕ at android.os.Looper.loop(Looper.java:211)
06-14 18:15:14.713  18195-18195/com.some.app W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5317)
06-14 18:15:14.713  18195-18195/com.some.app W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
06-14 18:15:14.713  18195-18195/com.some.app W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
06-14 18:15:14.713  18195-18195/com.some.app W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
06-14 18:15:14.713  18195-18195/com.some.app W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
06-14 18:15:14.713  18195-18195/com.some.app W/System.err﹕ Caused by: microsoft.aspnet.signalr.client.transport.NegotiationException: There was a problem in the negotiation with the server
06-14 18:15:14.714  18195-18195/com.some.app W/System.err﹕ at microsoft.aspnet.signalr.client.transport.HttpClientTransport$1.onResponse(HttpClientTransport.java:86)
06-14 18:15:14.714  18195-18195/com.some.app W/System.err﹕ at microsoft.aspnet.signalr.client.http.java.NetworkRunnable.run(NetworkRunnable.java:82)
06-14 18:15:14.714  18195-18195/com.some.app W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
06-14 18:15:14.714  18195-18195/com.some.app W/System.err﹕ Caused by: java.lang.NoClassDefFoundError: microsoft.aspnet.signalr.client.transport.WebsocketTransport$1
06-14 18:15:14.715  18195-18195/com.some.app W/System.err﹕ at microsoft.aspnet.signalr.client.transport.WebsocketTransport.start(WebsocketTransport.java:92)
06-14 18:15:14.715  18195-18195/com.some.app W/System.err﹕ at microsoft.aspnet.signalr.client.transport.AutomaticTransport.resolveTransport(AutomaticTransport.java:89)
06-14 18:15:14.715  18195-18195/com.some.app W/System.err﹕ at microsoft.aspnet.signalr.client.transport.AutomaticTransport.start(AutomaticTransport.java:143)
06-14 18:15:14.715  18195-18195/com.some.app W/System.err﹕ at microsoft.aspnet.signalr.client.Connection.startTransport(Connection.java:673)
06-14 18:15:14.715  18195-18195/com.some.app W/System.err﹕ at microsoft.aspnet.signalr.client.Connection.access$500(Connection.java:30)
06-14 18:15:14.715  18195-18195/com.some.app W/System.err﹕ at microsoft.aspnet.signalr.client.Connection$3.run(Connection.java:373)
06-14 18:15:14.715  18195-18195/com.some.app W/System.err﹕ at microsoft.aspnet.signalr.client.Connection$3.run(Connection.java:350)
06-14 18:15:14.715  18195-18195/com.some.app W/System.err﹕ at microsoft.aspnet.signalr.client.SignalRFuture.setResult(SignalRFuture.java:73)
06-14 18:15:14.715  18195-18195/com.some.app W/System.err﹕ at microsoft.aspnet.signalr.client.transport.HttpClientTransport$1.onResponse(HttpClientTransport.java:82)
06-14 18:15:14.715  18195-18195/com.some.app W/System.err﹕ ... 2 more

But this works fine (ServerSentEventsTransport):

```java
Platform.loadPlatformComponent(new AndroidPlatformComponent());
String server = "http://mysite.com/api/signalr";

HubConnection connection = new HubConnection(server, true);
HubProxy proxy = connection.createHubProxy("conversationHub");

HttpConnection httpConnection = new SignalrCustomConn(connection.getLogger());

try {
	connection.start(new ServerSentEventsTransport(connection.getLogger(), httpConnection)).get();
} catch (InterruptedException e) {
	e.printStackTrace();
} catch (ExecutionException e) {
	e.printStackTrace();
}

//Then call on() to handle the messages when they are received.
proxy.on("newConversationMessage", new SubscriptionHandler1<Payload>() {
	@Override
	public void run(Payload msg) {
		Log.d("result := ", msg.getText());
	}
}, Payload.class);
```

**Comment by tmedanovic** [comment]
1. Download java-websocket-1.3.1.jar from https://clojars.org/repo/org/java-websocket/java-websocket/1.3.1/ and put it in libs folder of your project
2. add to gradle: compile files('libs/java-websocket-1.3.1.jar')

**Comment by bdtuhin001** [comment]
does it really work?
there is no library for HTTPConnection in java-wesocket

**Comment by jasperrietrae** [comment]
@tmedanovic doesn't work for me, same error

**Comment by 4brunu** [comment]
We hit the same error and the solution proposed by @tmedanovic worked for us.
