### ISSUE TITLE
SignalR looses connection without any callback!

### ISSUE THREAD

**Issue by spartacus777** [SignalR/java-client#85]
I use your lib in my android project.
I have a connection, with headers supplied, via 

``` java
 authConnection.setCredentials(new Credentials() {
            @Override
            public void prepareRequest(Request request) {
                request.addHeader(AUTH_TOKEN, token);
            }
        });
```

I use ServerSentEventsTransport (WebsocketTransport was not able to 'eat' my headers, and I have got error in auth.)

My connection looses, without any callbacks, if i do not touch device(emulator) for some time (more than 45 sec) . Thread is just struck on   

``` java
result = hubProxy.invoke(String.class, methodName, objects).get();
```

I need your help very much, I almost waste a week trying to make SignalR work for me...

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
