### ISSUE TITLE
Reconnection problem when the Internet connection is lost

### ISSUE THREAD

**Issue by ugurcany** [SignalR/java-client#92]
We are having problem about reconnecting the SignalR server after we close/lose the Internet connection. We are setting the timeout duration at server side to 60 seconds, and expecting that our Android app, which uses SignalR java client, should try to reconnect the server for 60 seconds (since we set the timeout as such) after the device loses the Internet connection. However, when we close the Internet connection, the connection state directly changes from "Connected" to "Reconnecting" and then from "Reconnecting" to "Disconnected", without trying reconnection for 60 seconds. Our connection is a HubConnection and uses AutomaticTransport.

By the way, there is hope when we are using "LongPollingTransport", but we don't prefer to use it. If you have any idea how to solve this problem, we appreciate. Thanks.

**Comment by pranavmehta** [comment]
We've had a similar issue - for use, the connection got stuck in reconnecting state forever. Just watch for the connection stateChanged event, and manually close and start the connection when the connection goes into 'reconnecting" state. This is the only hack that worked for us.

```java
@Override
public void stateChanged(ConnectionState oldState, ConnectionState newState) {
    // TODO Auto-generated method stub
    if(newState==ConnectionState.Connected)
    {
        LogUtil.d("STATE CHANGED-CONNECTED!");
    }
    else if(newState==ConnectionState.Reconnecting)
    {
        LogUtil.d("STATE CHANGED-RECONNECTING!");
        // manually close the connection and reconnect here
    }
    else if(newState==ConnectionState.Disconnected)
    {
        LogUtil.d("STATE CHANGED-DISCONNECTED!");
    }
}
```

**Comment by ugurcany** [comment]
Closing connection is not the right call for us here since it causes us to lose incoming data during the time period passed in connection states "disconnected -> connecting --> connected". Anyway, thanks for the answer. We continue our way with http://socket.io/ which is more reliable and has more stable android client.

**Comment by regisdaniel** [comment]
Hello!


Are you using SignalR with C#? If yes, with cliente are you using?






Enviado do Email do Windows





De: Ugurcan Yildirim
Enviado: ‎terça-feira‎, ‎15‎ de ‎dezembro‎ de ‎2015 ‎05‎:‎42
Para: SignalR/java-client





Closing connection is not the right call for us here since it causes us to lose incoming data during the time period passed in connection states "disconnected -> connecting --> connected". Anyway, thanks for the answer. We continue our way with http://socket.io/ which is more reliable and has more stable android client.

**Comment by regisdaniel** [comment]
Hello @ugurcany !

Are you using Socket.IO with .NET? If yes, which client are you using?

Thanks!

**Comment by ugurcany** [comment]
We are using nodejs for Socket.IO server. Our clients are on Android and iOS platforms, both of which have their client libraries.

**Comment by midaslefkowitz** [comment]
@pranavmehta You're solution worked for me. I almost gave up after days of working at this!

**Comment by gooddayashok** [comment]
how to implement in android signalR service class if lost internet connection not connect ,how to solve these issue ? please give answer

**Comment by ik-j** [comment]
I am having this issue. Can someone plz share complete code for a Java client ? Altough I tried @pranavmehta solution but I am having no luck :(

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
