### ISSUE TITLE
A lot of TCP Remote port TIME_WAIT 

### ISSUE THREAD

**Issue by MinChanSike** [SignalR/java-client#97]
When I use Longpolling transport protocol, got a lot of **TIME_WAIT** in TCP Remote port 
while sending message continuously to server as custom _keep alive_.
A lot of connection and remote port are occur in background.
Try to solve it and trace SignalR-client-sdk source.
Close BufferedReader after _readLine_ in `readToEnd` method
under _package microsoft.aspnet.signalr.client.http;_ **_StreamResponse.java_**  , 
add `mReader.close();` 
What will impact for this fixed? Guess it's solve for TCP TIME_WAIT.

```
public String readToEnd() throws IOException {
        StringBuilder sb = new StringBuilder();
        String line = null;
        while ((line = mReader.readLine()) != null) {
            sb.append(line);
            sb.append("\n");
        }
        mReader.close(); //Add code
        return sb.toString();
    }
```

Plz see in screenshort TCP remote port TIME_WAIT.
https://i.imgsafe.org/fe70cbd.png

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
