### ISSUE TITLE
SignalR Connection Made but no Response from Server

### ISSUE THREAD

**Issue by NikSol** [SignalR/java-client#98]
Hi,

I am facing an issue where I have made a successful signalR connection and getting the Connection Id but not getting the Response back from the server.

The registered callback method hubProxy.on(....,...) is not getting called.

Kindly help me out if anyone has faced this kind of issue.

NikSol

**Comment by dengue8830** [comment]
same problem here D:

**Comment by umarF** [comment]
Same issue !
Can anyone help out ?

**Comment by dengue8830** [comment]
You must receive the same parameters that you have in the server call. Make a broadcast message without parameters and in your client receive the same without parameters

**Comment by umarF** [comment]
Hi,

The server sends me this,
name as string , message as string,  day as string and hour as string, avatar as string is url of avatar
So basically 5 params.

I am confused how should my method be..

HubProxy.on("method_name",Subscription Handler);


Could you help me out with this ?

**Comment by umarF** [comment]
I am able to send messages but dont receive any...

**Comment by dengue8830** [comment]
you have a suscription handler for each amount of params, you should send your params in a json an receive them with something like this:

 mHubProxy.on("event_name", new SubscriptionHandler1<Object>() {
            @Override
            public void run(final Object result) {
                Log.i("dispTaxiCancViajPasaj", "i am testing if the result is coming");
            }
        }, Object.class);

**Comment by umarF** [comment]
I am trying this:

```

        String CLIENT_METHOD_BROADAST_MESSAGE = "addNewMessageToPage";
        mHubProxy.on(CLIENT_METHOD_BROADAST_MESSAGE,
                new SubscriptionHandler1<CustomMessage>() {
                    @Override
                    public void run(final CustomMessage msg) {
                        final String finalMsg = msg.UserName + " says " + msg.Message;
                        // display Toast message
                        mHandler.post(new Runnable() {
                            @Override
                            public void run() {
                                Toast.makeText(getApplicationContext(), finalMsg, Toast.LENGTH_SHORT).show();
                            }
                        });
                    }
                }
                , CustomMessage.class);
```

Where, CustomMessage is defined as:

```
public class CustomMessage {
    public String UserName;
    public String Message;
    public String Mdate;
    public String MTime;
    public String userimage;
}
```



But still nothing...
What am I missing ? I can't get this .

**Comment by umarF** [comment]
I am getting an Array response from server.

**Comment by umarF** [comment]
I am getting an Array response from server.

I tried this too but doesnt work:

```
String CLIENT_METHOD_BROADAST_MESSAGE = "addNewMessageToPage";
        mHubProxy.on(CLIENT_METHOD_BROADAST_MESSAGE,
                new SubscriptionHandler1<String[]>() {
                    @Override
                    public void run(final String[] msg) {
                        final String finalMsg = msg[0] + " says " + msg[1];
                        Log.d("###", "run: ");
                        // display Toast message
                        mHandler.post(new Runnable() {
                            @Override
                            public void run() {
                                Log.d("###", "run: ");
                                Toast.makeText(getApplicationContext(), finalMsg, Toast.LENGTH_SHORT).show();
                            }
                        });
                    }
                }
                , String[].class);

    }
```


Here is my class and url and methods names that I am using.
Please help me out with this.
I would really appreciate.


```
public class SignalRService extends Service {
    private HubConnection mHubConnection;
    private HubProxy mHubProxy;
    private Handler mHandler; // to display Toast message
    private final IBinder mBinder = new LocalBinder(); // Binder given to clients
    private SubscriptionHandler1 handlerCon;

    public SignalRService() {
    }

    @Override
    public void onCreate() {
        super.onCreate();
        mHandler = new Handler(Looper.getMainLooper());
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        int result = super.onStartCommand(intent, flags, startId);
        startSignalR();
        return result;
    }

    @Override
    public void onDestroy() {
        mHubConnection.stop();
        super.onDestroy();
    }

    @Override
    public IBinder onBind(Intent intent) {
        // Return the communication channel to the service.
        startSignalR();
        return mBinder;
    }

    /**
     * Class used for the client Binder.  Because we know this service always
     * runs in the same process as its clients, we don't need to deal with IPC.
     */
    public class LocalBinder extends Binder {
        public SignalRService getService() {
            // Return this instance of SignalRService so clients can call public methods
            return SignalRService.this;
        }
    }

    /**
     * method for clients (activities)
     */
    public void sendMessage(String message) {
        String SERVER_METHOD_SEND = "send";
        mHubProxy.invoke(SERVER_METHOD_SEND,"911","ufo", "Android","http://d39kbiy71leyho.cloudfront.net/wp-content/uploads/2016/05/09170020/cats-politics-TN.jpg");
    }



    private void startSignalR() {
        Platform.loadPlatformComponent(new AndroidPlatformComponent());

        String serverUrl = "http://ryuktaro-001-site1.itempurl.com/signalr";
        mHubConnection = new HubConnection(serverUrl);
        String SERVER_HUB_CHAT = "chatHub";
        mHubProxy = mHubConnection.createHubProxy(SERVER_HUB_CHAT);
        ClientTransport clientTransport = new ServerSentEventsTransport(mHubConnection.getLogger());
        SignalRFuture<Void> signalRFuture = mHubConnection.start(clientTransport);

        try {
            signalRFuture.get();
        } catch (InterruptedException | ExecutionException e) {
            Log.e("##SimpleSignalR", e.toString());
            return;
        }

        sendMessage("Android!");



        String CLIENT_METHOD_BROADAST_MESSAGE = "addNewMessageToPage";
        mHubProxy.on(CLIENT_METHOD_BROADAST_MESSAGE,
                new SubscriptionHandler1<String[]>() {
                    @Override
                    public void run(final String[] msg) {
                        final String finalMsg = msg[0] + " says " + msg[1];
                        Log.d("###", "run: ");
                        // display Toast message
                        mHandler.post(new Runnable() {
                            @Override
                            public void run() {
                                Log.d("###", "run: ");
                                Toast.makeText(getApplicationContext(), finalMsg, Toast.LENGTH_SHORT).show();
                            }
                        });
                    }
                }
                , String[].class);

    }

   
}

```

**Comment by dengue8830** [comment]
you don't understand how singalr process the response. You must receive an Object as response and later parse it to your custom object.

Let's go step by step

 1) first make shure that your client are receiving the event, make a simple example to prove that:

In your server make a broadcast message TO ALL CLIENTS to that event name WITHOUT PARAMETERS

`Clients.event_name();`
(something like that, i cant remember the server code right now jaja)

And in your client you will listen to event_name WITHOUT PARAMETERS

```
mHubProxy.on("event_name", new SubscriptionHandler() {
            @Override
            public void run() {
                Log.i("event_name", "yes, it works");
            }
        });
```

If your client prints that log you can just continue with the next step, send parameters

2) to send parameters

in your server

`Clients.event_name("hi");`
(something like that ja)

in your client

```
mHubProxy.on("event_name", new SubscriptionHandler1<Object>() {
            @Override
            public void run(final Object result) {
                Log.i("event_name", "im receiving params :D");
                Log.i("event_name", result.toString());
            }
        }, Object.class);
```
please note that you must receive as Object

3) parse the result to a custom object

make a method like mine

public static JSONObject decodeResult(Object result) throws JSONException {
        if(result == null)
            return null;

        Gson gson = new GsonBuilder().serializeNulls().create();
        return new JSONObject(gson.toJson(result));
    }

now you can modify the client code to 

```
mHubProxy.on("event_name", new SubscriptionHandler1<Object>() {
            @Override
            public void run(final Object result) {
                Log.i("event_name", "im receiving params :D");
                Log.i("event_name", decodeResult(result).toString());
            }
        }, Object.class);
```

now you must parse de jsonobject to your custom object, something like this

```
JSONObject joResult = decodeResult(result);
MyObject myObject = new myObject();
myObject.setId(joResult.getLong("id"));
```

**Comment by umarF** [comment]
Ok thanks. I will get back to you once I do the above steps.
I have asked the backend developer to add logs to the server and empty parameter functions to test if the connection with Android is working. Strangely all of the code works on web and iOS but not with Android.

**Comment by umarFarooque** [comment]
The problem was in the callback method ( **mhubproxy.on()** )that I implemented. It doesnt receive any callbacks from server. I followed this [link](http://stackoverflow.com/a/40520578/2570153) and it helped me. The answer implements a different method connection.received() which is able to receive message callbacks from the server in my case.

**Comment by umarF** [comment]
The problem was in the callback method ( mhubproxy.on() )that I implemented. It doesnt receive any callbacks from server. I followed this [link](http://stackoverflow.com/a/40520578/2570153) and it helped me. The answer implements a different method connection.received() which is able to receive message callbacks from the server in my case.

**Comment by dengue8830** [comment]
That's strange, but if that works for you its fine

You must check you signalr lib version, i had a problem with my lib version when i triyng to upload the app to the playstore, you should try to upload a test app with your signalr libs to test this

**Comment by wspresto** [comment]
I was having a similar problem. Then I tried to specify the client transport object that you can pass to the hub proxy start method. I passed along Long Polling and it worked. Whenever I try to use websockets, it just hangs. Doing nothing.

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
