### ISSUE TITLE
SignalR not working in Android build made with TFS

### ISSUE THREAD

**Issue by nareninindia** [SignalR/java-client#99]
I generated the build using Android Studio.
SignalR events are coming correctly.

When I generated the build with same code using TFS (Team Foundation Server), the SignalR events are not coming.

The same question on Stackoverflow
http://stackoverflow.com/questions/37416281/signalr-events-not-coming-in-android-app-built-with-tfs

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
